name: huantran792020@gmail.com /lockscreennotificationsandroibigspeedRequest Id: ef747f11-87aa-4b91-ab40-fde4335a0a00
Correlation Id: b29de184-3b9b-4c55-8bd5-7c334d1db422
Timestamp: 2025-10-31T06:07:56Z
Message: AADSTS160011: Selected user account was invalid.
Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
